language: ruby
rvm:
    - 2.0
    - 2.1
    - 2.2
env:
    - DB=sqlite
    - DB=mysql
    - DB=postgresql
before_script:
    - cp config/database.test.yml config/database.yml
    - cp .env.example .env
    - bundle install
script:
    - RAILS_ENV=test bin/rake db:create --trace
    - RAILS_ENV=test bin/rake db:migrate --trace
    - RAILS_ENV=test bin/rake spec --trace
notifications:
  on_success: always  # options: [always|never|change] default: always
  on_failure: always  # options: [always|never|change] default: always
  on_start: false     # default: false
